// Word list — generated from word-list.csv
// FOOD and FOOD & DRINK merged into FOOD
const WORDS = [
  {id:1,arabic:"واحد",pronunciation:"waa-hid",english:"One",visual:"1️⃣",category:"NUMBERS"},
  {id:2,arabic:"اثنين",pronunciation:"ith-nayn",english:"Two",visual:"2️⃣",category:"NUMBERS"},
  {id:3,arabic:"ثلاثة",pronunciation:"tha-laa-tha",english:"Three",visual:"3️⃣",category:"NUMBERS"},
  {id:4,arabic:"أربعة",pronunciation:"ar-ba-a",english:"Four",visual:"4️⃣",category:"NUMBERS"},
  {id:5,arabic:"خمسة",pronunciation:"kham-sa",english:"Five",visual:"5️⃣",category:"NUMBERS"},
  {id:6,arabic:"ستة",pronunciation:"sit-ta",english:"Six",visual:"6️⃣",category:"NUMBERS"},
  {id:7,arabic:"سبعة",pronunciation:"sab-a",english:"Seven",visual:"7️⃣",category:"NUMBERS"},
  {id:8,arabic:"ثمانية",pronunciation:"tha-maa-nya",english:"Eight",visual:"8️⃣",category:"NUMBERS"},
  {id:9,arabic:"تسعة",pronunciation:"tis-a",english:"Nine",visual:"9️⃣",category:"NUMBERS"},
  {id:10,arabic:"عشرة",pronunciation:"ash-a-ra",english:"Ten",visual:"🔟",category:"NUMBERS"},
  {id:11,arabic:"أسود",pronunciation:"as-wad",english:"Black",visual:"⬛",category:"COLOURS"},
  {id:12,arabic:"أبيض",pronunciation:"ab-yad",english:"White",visual:"⬜",category:"COLOURS"},
  {id:13,arabic:"أحمر",pronunciation:"ah-mar",english:"Red",visual:"🔴",category:"COLOURS"},
  {id:14,arabic:"أخضر",pronunciation:"akh-dar",english:"Green",visual:"🟢",category:"COLOURS"},
  {id:15,arabic:"أزرق",pronunciation:"az-raq",english:"Blue",visual:"🔵",category:"COLOURS"},
  {id:16,arabic:"أصفر",pronunciation:"as-far",english:"Yellow",visual:"🟡",category:"COLOURS"},
  {id:17,arabic:"وردي",pronunciation:"war-di",english:"Pink",visual:"🩷",category:"COLOURS"},
  {id:18,arabic:"تمن",pronunciation:"tim-man",english:"Rice",visual:"🍚",category:"FOOD"},
  {id:19,arabic:"فراولة",pronunciation:"fa-raw-la",english:"Strawberry",visual:"🍓",category:"FOOD"},
  {id:20,arabic:"تفاح",pronunciation:"tuf-fah",english:"Apple",visual:"🍎",category:"FOOD"},
  {id:21,arabic:"تمر",pronunciation:"tam-mar",english:"Dates (fruit)",visual:"🌴",category:"FOOD"},
  {id:22,arabic:"سكر",pronunciation:"suk-kar",english:"Sugar",visual:"🍬",category:"FOOD"},
  {id:23,arabic:"شاي",pronunciation:"shaay",english:"Tea",visual:"🍵",category:"FOOD"},
  {id:24,arabic:"أكل",pronunciation:"ak-kal",english:"Food / to eat",visual:"🍽️",category:"FOOD"},
  {id:25,arabic:"ماي",pronunciation:"maay",english:"Water",visual:"💧",category:"FOOD"},
  {id:26,arabic:"فواكه",pronunciation:"faw-aa-keh",english:"Fruits",visual:"🍇",category:"FOOD"},
  {id:27,arabic:"دجاج",pronunciation:"da-jaaj",english:"Chicken",visual:"🍗",category:"FOOD"},
  {id:28,arabic:"لحم",pronunciation:"la-hem",english:"Meat",visual:"🥩",category:"FOOD"},
  {id:29,arabic:"خضار",pronunciation:"khu-daar",english:"Vegetables",visual:"🥦",category:"FOOD"},
  {id:30,arabic:"بطيخ",pronunciation:"bat-teekh",english:"Watermelon",visual:"🍉",category:"FOOD"},
  {id:99,arabic:"حليب",pronunciation:"ha-leeb",english:"Milk",visual:"🥛",category:"FOOD"},
  {id:100,arabic:"خبز",pronunciation:"khu-biz",english:"Bread",visual:"🍞",category:"FOOD"},
  {id:101,arabic:"قهوة",pronunciation:"gah-wa",english:"Coffee",visual:"☕",category:"FOOD"},
  {id:102,arabic:"بيضة",pronunciation:"bay-tha",english:"Egg",visual:"🥚",category:"FOOD"},
  {id:103,arabic:"جبن",pronunciation:"jib-in",english:"Cheese",visual:"🧀",category:"FOOD"},
  {id:104,arabic:"ملح",pronunciation:"mi-lih",english:"Salt",visual:"🧂",category:"FOOD"},
  {id:105,arabic:"سمك",pronunciation:"si-mach",english:"Fish",visual:"🐟",category:"FOOD"},
  {id:106,arabic:"حلو",pronunciation:"hil-wu",english:"Sweet",visual:"🍭",category:"FOOD"},
  {id:107,arabic:"زيت",pronunciation:"zayt",english:"Oil",visual:"🫙",category:"FOOD"},
  {id:108,arabic:"عسل",pronunciation:"a-sal",english:"Honey",visual:"🍯",category:"FOOD"},
  {id:31,arabic:"ياكل",pronunciation:"yaa-kul",english:"He eats",visual:"😋",category:"ACTIONS"},
  {id:32,arabic:"يشرب",pronunciation:"yash-rab",english:"He drinks",visual:"🥤",category:"ACTIONS"},
  {id:33,arabic:"ينام",pronunciation:"ya-naam",english:"He sleeps",visual:"😴",category:"ACTIONS"},
  {id:34,arabic:"يلعب",pronunciation:"yal-ab",english:"He plays",visual:"⚽",category:"ACTIONS"},
  {id:35,arabic:"يمشي",pronunciation:"yam-shi",english:"He walks",visual:"🚶",category:"ACTIONS"},
  {id:36,arabic:"يركض",pronunciation:"yar-kud",english:"He runs",visual:"🏃",category:"ACTIONS"},
  {id:37,arabic:"يسبح",pronunciation:"yas-bah",english:"He swims",visual:"🏊",category:"ACTIONS"},
  {id:38,arabic:"يذهب",pronunciation:"yath-hab",english:"He goes",visual:"➡️",category:"ACTIONS"},
  {id:129,arabic:"أريد",pronunciation:"a-reed",english:"I want",visual:"🙋",category:"MY ACTIONS"},
  {id:130,arabic:"أروح",pronunciation:"a-rooh",english:"I go",visual:"🚶",category:"MY ACTIONS"},
  {id:131,arabic:"أجي",pronunciation:"a-jee",english:"I come",visual:"🏃",category:"MY ACTIONS"},
  {id:132,arabic:"آكل",pronunciation:"aa-kul",english:"I eat",visual:"😋",category:"MY ACTIONS"},
  {id:133,arabic:"أشرب",pronunciation:"a-shrab",english:"I drink",visual:"🥤",category:"MY ACTIONS"},
  {id:134,arabic:"أنام",pronunciation:"a-naam",english:"I sleep",visual:"😴",category:"MY ACTIONS"},
  {id:135,arabic:"أحب",pronunciation:"a-hib",english:"I love",visual:"💖",category:"MY ACTIONS"},
  {id:136,arabic:"أشوف",pronunciation:"a-shoof",english:"I see",visual:"👀",category:"MY ACTIONS"},
  {id:137,arabic:"أسمع",pronunciation:"as-ma",english:"I hear",visual:"👂",category:"MY ACTIONS"},
  {id:138,arabic:"أتكلم",pronunciation:"at-kal-lam",english:"I speak",visual:"🗣️",category:"MY ACTIONS"},
  {id:139,arabic:"أعرف",pronunciation:"a-ruf",english:"I know",visual:"🤔",category:"MY ACTIONS"},
  {id:140,arabic:"أقرأ",pronunciation:"aq-ra",english:"I read",visual:"📖",category:"MY ACTIONS"},
  {id:141,arabic:"أكتب",pronunciation:"ak-tub",english:"I write",visual:"✏️",category:"MY ACTIONS"},
  {id:142,arabic:"ألعب",pronunciation:"al-ab",english:"I play",visual:"🧸",category:"MY ACTIONS"},
  {id:143,arabic:"أضحك",pronunciation:"ath-hak",english:"I laugh",visual:"😂",category:"MY ACTIONS"},
  {id:39,arabic:"فرحان",pronunciation:"far-haan",english:"Happy",visual:"😄",category:"FEELINGS"},
  {id:40,arabic:"زعلان",pronunciation:"za-laan",english:"Upset / sad",visual:"😢",category:"FEELINGS"},
  {id:41,arabic:"تعبان",pronunciation:"ta-baan",english:"Tired",visual:"😩",category:"FEELINGS"},
  {id:42,arabic:"جوعان",pronunciation:"jaw-aan",english:"Hungry",visual:"🤤",category:"FEELINGS"},
  {id:43,arabic:"شبعان",pronunciation:"shab-aan",english:"Full (food)",visual:"😌",category:"FEELINGS"},
  {id:44,arabic:"نعسان",pronunciation:"naas-aan",english:"Sleepy",visual:"😌",category:"FEELINGS"},
  {id:45,arabic:"جميل",pronunciation:"ja-meel",english:"Beautiful",visual:"✨",category:"DESCRIPTIONS"},
  {id:46,arabic:"جيد جداً",pronunciation:"jay-yid jid-dan",english:"Very good",visual:"👍",category:"DESCRIPTIONS"},
  {id:47,arabic:"ممتاز",pronunciation:"mum-taaz",english:"Excellent",visual:"🌟",category:"DESCRIPTIONS"},
  {id:48,arabic:"زين",pronunciation:"zayn",english:"Good / nice",visual:"😊",category:"DESCRIPTIONS"},
  {id:49,arabic:"موزين",pronunciation:"maw-zeen",english:"Not good",visual:"⚖️",category:"DESCRIPTIONS"},
  {id:50,arabic:"خوش",pronunciation:"hkowsh",english:"Ok / Fine",visual:"👌",category:"DESCRIPTIONS"},
  {id:51,arabic:"مو خوش",pronunciation:"maw-khowsh",english:"Not Good",visual:"👎",category:"DESCRIPTIONS"},
  {id:52,arabic:"سيارة",pronunciation:"say-yaa-ra",english:"Car",visual:"🚗",category:"PLACES & THINGS"},
  {id:53,arabic:"بيت",pronunciation:"bayt",english:"House",visual:"🏠",category:"PLACES & THINGS"},
  {id:54,arabic:"شارع",pronunciation:"shaa-ri",english:"Street",visual:"🛣️",category:"PLACES & THINGS"},
  {id:55,arabic:"علم",pronunciation:"a-lam",english:"Flag",visual:"🚩",category:"PLACES & THINGS"},
  {id:56,arabic:"غرفة",pronunciation:"ghur-fa",english:"Room",visual:"🛏️",category:"PLACES & THINGS"},
  {id:57,arabic:"شجرة",pronunciation:"sha-ja-ra",english:"Tree",visual:"🌳",category:"PLACES & THINGS"},
  {id:58,arabic:"كومبيوتر",pronunciation:"kom-pyoo-ter",english:"Computer",visual:"💻",category:"PLACES & THINGS"},
  {id:59,arabic:"ميز",pronunciation:"meaz",english:"Table / Desk",visual:"✨",category:"PLACES & THINGS"},
  {id:60,arabic:"عشب",pronunciation:"ush-b",english:"Grass",visual:"🌿",category:"PLACES & THINGS"},
  {id:61,arabic:"يوم",pronunciation:"yawm",english:"Day",visual:"☀️",category:"TIME"},
  {id:62,arabic:"ساعة",pronunciation:"saa-a",english:"Hour / clock",visual:"⏰",category:"TIME"},
  {id:63,arabic:"وقت",pronunciation:"waqt",english:"Time",visual:"⌚",category:"TIME"},
  {id:64,arabic:"سرعة",pronunciation:"sur-a",english:"Speed",visual:"⚡",category:"TIME"},
  {id:65,arabic:"عام / سنة",pronunciation:"aam / sa-na",english:"Year",visual:"📅",category:"TIME"},
  {id:66,arabic:"مشكلة",pronunciation:"mush-ki-la",english:"Problem",visual:"⚠️",category:"USEFUL"},
  {id:67,arabic:"أكو",pronunciation:"aa-koo",english:"There is",visual:"✅",category:"USEFUL"},
  {id:68,arabic:"ماكو",pronunciation:"maa-koo",english:"There isn't",visual:"❌",category:"USEFUL"},
  {id:69,arabic:"مرحبا",pronunciation:"Marhaba",english:"Hello",visual:"👋",category:"USEFUL"},
  {id:70,arabic:"سلام عليكم",pronunciation:"Salam Alaykum",english:"Hello",visual:"👋",category:"USEFUL"},
  {id:74,arabic:"هذا",pronunciation:"Hatha",english:"This",visual:"👉",category:"USEFUL"},
  {id:76,arabic:"كلش",pronunciation:"kulish",english:"Very",visual:"💯",category:"USEFUL"},
  {id:151,arabic:"شكرا",pronunciation:"shuk-ran",english:"Thank you",visual:"🙏",category:"GREETINGS"},
  {id:152,arabic:"عفوا",pronunciation:"af-wan",english:"You're welcome",visual:"😊",category:"GREETINGS"},
  {id:153,arabic:"من فضلك",pronunciation:"min fath-lak",english:"Please",visual:"🙇",category:"GREETINGS"},
  {id:154,arabic:"آسف",pronunciation:"aa-sif",english:"Sorry",visual:"😔",category:"GREETINGS"},
  {id:155,arabic:"ايه",pronunciation:"ee",english:"Yes",visual:"✅",category:"GREETINGS"},
  {id:156,arabic:"لا",pronunciation:"laa",english:"No",visual:"❌",category:"GREETINGS"},
  {id:157,arabic:"طيب",pronunciation:"tay-yib",english:"Okay / good",visual:"👍",category:"GREETINGS"},
  {id:158,arabic:"يلا",pronunciation:"ya-lla",english:"Let's go",visual:"🏃",category:"GREETINGS"},
  {id:159,arabic:"بس",pronunciation:"bas",english:"Just / enough",visual:"✋",category:"GREETINGS"},
  {id:160,arabic:"باجر",pronunciation:"baa-chir",english:"Tomorrow",visual:"🗓️",category:"GREETINGS"},
  {id:77,arabic:"شلونك",pronunciation:"shloo-nak",english:"How are you?",visual:"🤝",category:"GREETINGS"},
  {id:161,arabic:"مدرسة",pronunciation:"mad-ra-sa",english:"School",visual:"🏫",category:"PLACES"},
  {id:162,arabic:"مستشفى",pronunciation:"mus-tash-fa",english:"Hospital",visual:"🏥",category:"PLACES"},
  {id:163,arabic:"سوق",pronunciation:"sooq",english:"Market",visual:"🛒",category:"PLACES"},
  {id:164,arabic:"مطعم",pronunciation:"mat-am",english:"Restaurant",visual:"🍽️",category:"PLACES"},
  {id:165,arabic:"دكان",pronunciation:"du-kaan",english:"Shop",visual:"🏪",category:"PLACES"},
  {id:166,arabic:"حديقة",pronunciation:"ha-dee-qa",english:"Garden / park",visual:"🌳",category:"PLACES"},
  {id:167,arabic:"مسجد",pronunciation:"mas-jid",english:"Mosque",visual:"🕌",category:"PLACES"},
  {id:168,arabic:"مطار",pronunciation:"ma-taar",english:"Airport",visual:"✈️",category:"PLACES"},
  {id:169,arabic:"مدينة",pronunciation:"ma-dee-na",english:"City",visual:"🏙️",category:"PLACES"},
  {id:170,arabic:"بحر",pronunciation:"ba-har",english:"Sea",visual:"🌊",category:"PLACES"},
  {id:171,arabic:"مطر",pronunciation:"mu-tar",english:"Rain",visual:"🌧️",category:"WEATHER"},
  {id:172,arabic:"حر",pronunciation:"har",english:"Hot",visual:"🥵",category:"WEATHER"},
  {id:173,arabic:"برد",pronunciation:"ba-rid",english:"Cold",visual:"🥶",category:"WEATHER"},
  {id:174,arabic:"ريح",pronunciation:"reeh",english:"Wind",visual:"🌬️",category:"WEATHER"},
  {id:175,arabic:"ثلج",pronunciation:"thalj",english:"Snow",visual:"❄️",category:"WEATHER"},
  {id:176,arabic:"نجم",pronunciation:"nij-im",english:"Star",visual:"⭐",category:"WEATHER"},
  {id:177,arabic:"سماء",pronunciation:"sa-ma",english:"Sky",visual:"☁️",category:"WEATHER"},
  {id:178,arabic:"نار",pronunciation:"naar",english:"Fire",visual:"🔥",category:"WEATHER"},
  {id:71,arabic:"قمر",pronunciation:"qa-mar",english:"Moon",visual:"🌙",category:"NATURE"},
  {id:72,arabic:"شمس",pronunciation:"Shams",english:"Sun",visual:"☀️",category:"NATURE"},
  {id:73,arabic:"أنا",pronunciation:"Ana / ani",english:"I",visual:"✨",category:"NATURE"},
  {id:75,arabic:"هو / هي",pronunciation:"Hooe / Heea",english:"He / She",visual:"✨",category:"NATURE"},
  {id:78,arabic:"شكو ماكو",pronunciation:"Shakoo-makoo",english:"How are you going?",visual:"👋",category:"NATURE"},
  {id:79,arabic:"بابا",pronunciation:"baa-ba",english:"Dad",visual:"👨",category:"FAMILY"},
  {id:80,arabic:"ماما",pronunciation:"maa-ma",english:"Mom",visual:"👩",category:"FAMILY"},
  {id:81,arabic:"أخ",pronunciation:"akh",english:"Brother",visual:"👦",category:"FAMILY"},
  {id:82,arabic:"أخت",pronunciation:"ukh-ut",english:"Sister",visual:"👧",category:"FAMILY"},
  {id:83,arabic:"جدو",pronunciation:"jid-doo",english:"Grandfather",visual:"👴",category:"FAMILY"},
  {id:84,arabic:"جدة",pronunciation:"jid-da",english:"Grandmother",visual:"👵",category:"FAMILY"},
  {id:85,arabic:"عمو",pronunciation:"am-mu",english:"Uncle (paternal)",visual:"🧔",category:"FAMILY"},
  {id:86,arabic:"عمة",pronunciation:"am-ma",english:"Aunt (paternal)",visual:"👩‍🦰",category:"FAMILY"},
  {id:87,arabic:"خال",pronunciation:"khaal",english:"Uncle (maternal)",visual:"🧔‍♂️",category:"FAMILY"},
  {id:88,arabic:"خالة",pronunciation:"khaa-la",english:"Aunt (maternal)",visual:"👩‍🦱",category:"FAMILY"},
  {id:89,arabic:"راس",pronunciation:"raas",english:"Head",visual:"🧠",category:"BODY"},
  {id:90,arabic:"عين",pronunciation:"ayn",english:"Eye",visual:"👁️",category:"BODY"},
  {id:91,arabic:"أذن",pronunciation:"i-thin",english:"Ear",visual:"👂",category:"BODY"},
  {id:92,arabic:"فم",pronunciation:"fum",english:"Mouth",visual:"👄",category:"BODY"},
  {id:93,arabic:"يد",pronunciation:"eed",english:"Hand",visual:"✋",category:"BODY"},
  {id:94,arabic:"رجل",pronunciation:"rij-il",english:"Leg / foot",visual:"🦵",category:"BODY"},
  {id:95,arabic:"شعر",pronunciation:"sha-ar",english:"Hair",visual:"💇",category:"BODY"},
  {id:96,arabic:"أنف",pronunciation:"an-if",english:"Nose",visual:"👃",category:"BODY"},
  {id:97,arabic:"قلب",pronunciation:"ga-lib",english:"Heart",visual:"❤️",category:"BODY"},
  {id:98,arabic:"بطن",pronunciation:"ba-tin",english:"Tummy",visual:"🫃",category:"BODY"},
  {id:109,arabic:"كلب",pronunciation:"chal-ib",english:"Dog",visual:"🐶",category:"ANIMALS"},
  {id:110,arabic:"بزون",pronunciation:"bi-zoon",english:"Cat",visual:"🐱",category:"ANIMALS"},
  {id:111,arabic:"حصان",pronunciation:"hu-saan",english:"Horse",visual:"🐴",category:"ANIMALS"},
  {id:112,arabic:"طير",pronunciation:"tayr",english:"Bird",visual:"🐦",category:"ANIMALS"},
  {id:113,arabic:"بقرة",pronunciation:"ba-ga-ra",english:"Cow",visual:"🐄",category:"ANIMALS"},
  {id:114,arabic:"خروف",pronunciation:"khi-roof",english:"Sheep",visual:"🐑",category:"ANIMALS"},
  {id:115,arabic:"أسد",pronunciation:"a-sad",english:"Lion",visual:"🦁",category:"ANIMALS"},
  {id:116,arabic:"فيل",pronunciation:"feel",english:"Elephant",visual:"🐘",category:"ANIMALS"},
  {id:117,arabic:"دب",pronunciation:"dub",english:"Bear",visual:"🐻",category:"ANIMALS"},
  {id:118,arabic:"أرنب",pronunciation:"ar-nab",english:"Rabbit",visual:"🐰",category:"ANIMALS"},
  {id:119,arabic:"قميص",pronunciation:"qa-mees",english:"Shirt",visual:"👕",category:"HOME & CLOTHES"},
  {id:120,arabic:"بنطرون",pronunciation:"ban-ta-roon",english:"Pants",visual:"👖",category:"HOME & CLOTHES"},
  {id:121,arabic:"جزمة",pronunciation:"jaz-ma",english:"Shoes",visual:"👟",category:"HOME & CLOTHES"},
  {id:122,arabic:"باب",pronunciation:"baab",english:"Door",visual:"🚪",category:"HOME & CLOTHES"},
  {id:123,arabic:"شباك",pronunciation:"shu-baach",english:"Window",visual:"🪟",category:"HOME & CLOTHES"},
  {id:124,arabic:"كرسي",pronunciation:"kur-see",english:"Chair",visual:"🪑",category:"HOME & CLOTHES"},
  {id:125,arabic:"مفتاح",pronunciation:"mif-taah",english:"Key",visual:"🔑",category:"HOME & CLOTHES"},
  {id:126,arabic:"موبايل",pronunciation:"moo-baayl",english:"Mobile phone",visual:"📱",category:"HOME & CLOTHES"},
  {id:127,arabic:"تلفزيون",pronunciation:"tal-faz-yoon",english:"Television",visual:"📺",category:"HOME & CLOTHES"},
  {id:128,arabic:"سرير",pronunciation:"sa-reer",english:"Bed",visual:"🛏️",category:"HOME & CLOTHES"},
  {id:144,arabic:"شنو",pronunciation:"shnoo",english:"What?",visual:"❓",category:"QUESTIONS"},
  {id:145,arabic:"منو",pronunciation:"mi-noo",english:"Who?",visual:"🙋",category:"QUESTIONS"},
  {id:146,arabic:"وين",pronunciation:"wayn",english:"Where?",visual:"📍",category:"QUESTIONS"},
  {id:147,arabic:"شوكت",pronunciation:"shwa-kit",english:"When?",visual:"⏰",category:"QUESTIONS"},
  {id:148,arabic:"ليش",pronunciation:"laysh",english:"Why?",visual:"🤷",category:"QUESTIONS"},
  {id:149,arabic:"شكد",pronunciation:"sh-gad",english:"How much?",visual:"💰",category:"QUESTIONS"},
  {id:150,arabic:"هسه",pronunciation:"his-sa",english:"Now",visual:"⏱️",category:"QUESTIONS"},
];

const CATEGORIES = [...new Set(WORDS.map(w => w.category))];

// Category metadata: label (bilingual), emoji, pastel colour
const CATEGORY_META = {
  "NUMBERS":        { en: "Numbers",        ar: "الأرقام",     emoji: "🔢", color: "#FFF0CC" },
  "COLOURS":        { en: "Colours",        ar: "الألوان",     emoji: "🎨", color: "#FFE4F0" },
  "FOOD":           { en: "Food & Drink",   ar: "الأكل والشرب",emoji: "🍎", color: "#E8F5E9" },
  "ACTIONS":        { en: "Actions",        ar: "الأفعال",     emoji: "⚽", color: "#E3F2FD" },
  "MY ACTIONS":     { en: "My Actions",     ar: "أفعالي",      emoji: "🙋", color: "#EDE7F6" },
  "FEELINGS":       { en: "Feelings",       ar: "المشاعر",     emoji: "😄", color: "#FFF9C4" },
  "DESCRIPTIONS":   { en: "Descriptions",   ar: "الأوصاف",     emoji: "✨", color: "#F3E5F5" },
  "PLACES & THINGS":{ en: "Places & Things",ar: "أماكن وأشياء",emoji: "🏠", color: "#E0F7FA" },
  "TIME":           { en: "Time",           ar: "الوقت",       emoji: "⏰", color: "#FBE9E7" },
  "USEFUL":         { en: "Useful Words",   ar: "كلمات مفيدة", emoji: "💡", color: "#F1F8E9" },
  "GREETINGS":      { en: "Greetings",      ar: "التحيات",     emoji: "👋", color: "#E8EAF6" },
  "PLACES":         { en: "Places",         ar: "الأماكن",     emoji: "🏙️", color: "#E0F2F1" },
  "WEATHER":        { en: "Weather",        ar: "الطقس",       emoji: "🌤️", color: "#E3F2FD" },
  "NATURE":         { en: "Nature",         ar: "الطبيعة",     emoji: "🌿", color: "#F9FBE7" },
  "FAMILY":         { en: "Family",         ar: "العائلة",     emoji: "👨‍👩‍👧", color: "#FCE4EC" },
  "BODY":           { en: "Body",           ar: "الجسم",       emoji: "🫶", color: "#FFF3E0" },
  "ANIMALS":        { en: "Animals",        ar: "الحيوانات",   emoji: "🐾", color: "#E8F5E9" },
  "HOME & CLOTHES": { en: "Home & Clothes", ar: "البيت والملابس",emoji:"🏡",color: "#FFF8E1" },
  "QUESTIONS":      { en: "Questions",      ar: "الأسئلة",     emoji: "❓", color: "#F3E5F5" },
};

function getWordsByCategory(cat) {
  return WORDS.filter(w => w.category === cat);
}

function getRandomWords(count, excludeIds = []) {
  const pool = WORDS.filter(w => !excludeIds.includes(w.id));
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

function getDistractors(correctWord, count = 3) {
  // Prefer same-category distractors, fall back to any
  const sameCat = WORDS.filter(w => w.category === correctWord.category && w.id !== correctWord.id);
  const others = WORDS.filter(w => w.category !== correctWord.category);
  const pool = [...sameCat.sort(() => Math.random() - 0.5), ...others.sort(() => Math.random() - 0.5)];
  return pool.slice(0, count);
}
